<?php
echo '<div id="containter"';
	echo '<div class="row">';
		echo '<div class="col-sm-6">';
			echo '<div class"panel panel-default" id="panel1" onmouseover="panelOn(this.id)" onMouseOut="panelOff(this.id)">';
				echo '<div class="panel-heading">Indroductory</div>';
					echo '<div class="panel-body">';
						echo 'Hello and welcome to my web page!<br>';
						echo 'I am a senior at UTSA!<br>';
						echo 'I will be graduating by the end of the year! WOOHOO!<br>';
						echo 'I hope to work for a company that i enjoy.<br>';
					echo '</div>';
			echo '</div>';
		echo '</div>';
		echo '<div class="col-md-6">';
			echo '<div class"panel panel-default" id="panel2" onmouseover="panelOn(this.id)" onMouseOut="panelOff(this.id)">';
				echo '<div class="panel-heading">Interests</div>';
					echo '<div class="panel-body">';
						echo 'My interests are:<br>';
						echo 'Cooking<br>';
						echo 'Video Games<br>';
						echo 'Tech<br>';
						echo 'Esports<br>';
					echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</div>';
	echo '<div class"panel panel-default" id="panel3" onmouseover="panelOn(this.id)" onMouseOut="panelOff(this.id)">';
		echo '<div class="panel-heading">Harry Potter Filler</div>';
			echo '<div class="panel-body">';
				echo 'Please Enjoy the opening scene of Harry Potter and the Sorcerers Stone:<br>';
				echo '<br>	';							
				echo '[There is a motor sound, and the two professors look up to see a flying motorcycle coming down from the air. It skids on the street and halts. A large man with shoulder length black hair and beard named Rubeus Hagrid takes off his goggles.]<br>	';	
				echo '<br>';
				echo 'Hagrid: Professor Dumbledore, Sir. Professor McGonagall.<br>';
				echo '<br>';
				echo 'Dumbledore: No problems, I trust, Hagrid?<br>';
				echo '<br>';
				echo 'Hagrid: No, sir. Little tyke fell asleep just as we were flying over Bristol. Heh. Try not to wake him. There you go.<br>';
				echo '<br>';
				echo '[Hagrid hands a baby wrapped in a bundle over to Dumbledore.]<br>';
				echo '<br>';
				echo 'McGonagall: Albus, do you really think its safe, leaving him with these people? Ive watched them all day. Theyre the worst sort of Muggles imaginable. They really are...<br>';
				echo '<br>';
				echo 'Dumbledore: The only family he has.<br>';
				echo '<br>';
				echo '[They stop outside a house which is 4 Privet Drive.]<br>';
				echo '<br>';
				echo 'McGonagall: This boy will be famous. There wont be a child in our world who doesnt know his name.<br>';
				echo '<br>';
				echo 'Dumbledore: Exactly. Hes better off growing up away from all that. Until he is ready.<br>';
				echo '<br>';
				echo '[Dumbledore places the baby on the ground slowly. Hagrid sniffles, he is sobbing a little. He clears his throat.]<br>';
				echo '<br>';
				echo 'Dumbledore: There, there, Hagrid. Its not really goodbye, after all.<br>';
				echo '<br>';
				echo '[Hagrid nods. Dumbledore takes a letter and places it on the baby, who is now at the foot of the door.]<br>';
				echo '<br>';
				echo 'Dumbledore: Good luck...Harry Potter.<br>';
				echo '<br>';
				echo '[The baby has a lightning-bolt shaped scar on his forehead. The camera slowly zooms towards the scar which glows brightly and it immediately flashes, transitioning to a stormy cloud sky. The films title in metallic gold zooms out around the camera, and lightning flashes to brighten it up. Then, the lightning flashes engulf the screen, transitioning it to the present time.]<br>';
			echo '</div>';
	echo '</div>';
echo '</div>';
?>
